"""
Substance Abuse Visualizations
Creates comprehensive visualizations from filtered substance abuse data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

DOVE_HOME = Path(__file__).resolve().parents[2]
IDOH_DATA = DOVE_HOME / "data_by_criteria/02_access_health_social_services/indiana_hospital_discharge"
OUTPUT_DIR = IDOH_DATA / "outputs/data_exports"
VIZ_DIR = IDOH_DATA / "outputs/visualizations"

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.facecolor'] = 'white'

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def load_processed_data():
    """Load CSV files generated by filter_substance_abuse.py"""
    print("\n" + "="*80)
    print("LOADING PROCESSED SUBSTANCE ABUSE DATA")
    print("="*80)
    
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    substance_diag = pd.read_csv(OUTPUT_DIR / 'substance_abuse_by_diagnosis.csv')
    category_summary = pd.read_csv(OUTPUT_DIR / 'substance_abuse_category_summary.csv')
    hospital_summary = pd.read_csv(OUTPUT_DIR / 'substance_abuse_hospital_summary.csv')
    hospital_category = pd.read_csv(OUTPUT_DIR / 'substance_abuse_by_hospital_category.csv')
    hospital_payer = pd.read_csv(OUTPUT_DIR / 'substance_abuse_by_hospital_payer.csv')
    payer_summary = pd.read_csv(OUTPUT_DIR / 'substance_abuse_payer_summary.csv')
    msdrg_summary = pd.read_csv(OUTPUT_DIR / 'substance_abuse_msdrg_summary.csv')
    
    print(f"✓ Loaded all summary CSV files")
    return substance_diag, category_summary, hospital_summary, hospital_category, hospital_payer, payer_summary, msdrg_summary

def plot_substance_categories(category_summary):
    """1. Substance category breakdown with admission counts"""
    fig, ax = plt.subplots(figsize=(14, 8))
    
    data = category_summary.sort_values('PATS', ascending=True)
    colors = plt.cm.Spectral(np.linspace(0, 1, len(data)))
    bars = ax.barh(data['SUBSTANCE_CATEGORY'], data['PATS'], color=colors)
    
    ax.set_xlabel('Number of Admissions', fontsize=12, fontweight='bold')
    ax.set_title('Substance Abuse & Overdose Admissions by Category\nIndiana 2024', 
                 fontsize=14, fontweight='bold', pad=20)
    ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x/1000)}K'))
    
    for i, (bar, val) in enumerate(zip(bars, data['PATS'])):
        ax.text(val + 200, bar.get_y() + bar.get_height()/2, 
               f'{int(val):,}', va='center', fontweight='bold', fontsize=10)
    
    plt.tight_layout()
    VIZ_DIR.mkdir(parents=True, exist_ok=True)
    plt.savefig(VIZ_DIR / '01_substance_categories.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 01_substance_categories.png")
    plt.close()

def plot_category_costs(category_summary):
    """2. Average charge and LOS by substance category"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))
    
    data = category_summary.sort_values('AVG_CHARGE', ascending=True)
    colors = plt.cm.RdYlGn_r(np.linspace(0.3, 0.7, len(data)))
    
    # Average charge
    bars1 = ax1.barh(data['SUBSTANCE_CATEGORY'], data['AVG_CHARGE'], color=colors)
    ax1.set_xlabel('Average Charge per Admission (USD)', fontsize=11, fontweight='bold')
    ax1.set_title('Average Cost by Substance Category', fontsize=12, fontweight='bold', pad=15)
    ax1.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    
    for bar, val in zip(bars1, data['AVG_CHARGE']):
        ax1.text(val + 1000, bar.get_y() + bar.get_height()/2, 
                f'${val:,.0f}', va='center', fontweight='bold', fontsize=9)
    
    # Average LOS
    data_los = category_summary.sort_values('AVG_LOS', ascending=True)
    colors_los = plt.cm.Blues(np.linspace(0.4, 0.9, len(data_los)))
    bars2 = ax2.barh(data_los['SUBSTANCE_CATEGORY'], data_los['AVG_LOS'], color=colors_los)
    ax2.set_xlabel('Average Length of Stay (days)', fontsize=11, fontweight='bold')
    ax2.set_title('Average Hospital Stay by Substance Category', fontsize=12, fontweight='bold', pad=15)
    
    for bar, val in zip(bars2, data_los['AVG_LOS']):
        ax2.text(val + 0.1, bar.get_y() + bar.get_height()/2, 
                f'{val:.2f}', va='center', fontweight='bold', fontsize=9)
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '02_category_costs_los.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 02_category_costs_los.png")
    plt.close()

def plot_top_hospitals(hospital_summary):
    """3. Top hospitals with most substance abuse admissions"""
    fig, ax = plt.subplots(figsize=(14, 9))
    
    data = hospital_summary.head(20)
    colors = plt.cm.viridis(np.linspace(0, 1, len(data)))
    bars = ax.barh([f"Hospital {int(h)}" for h in data['HOSPITAL_ID']], 
                   data['PATS'], color=colors)
    
    ax.set_xlabel('Number of Substance Abuse Admissions', fontsize=12, fontweight='bold')
    ax.set_title('Top 20 Hospitals by Substance Abuse Admissions', fontsize=14, fontweight='bold', pad=20)
    ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x/1000)}K'))
    
    for bar, val in zip(bars, data['PATS']):
        ax.text(val + 20, bar.get_y() + bar.get_height()/2, 
               f'{int(val):,}', va='center', fontweight='bold', fontsize=9)
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '03_top_hospitals_substance.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 03_top_hospitals_substance.png")
    plt.close()

def plot_hospital_costs(hospital_summary):
    """4. Hospital cost analysis - charge vs admission volume"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 7))
    
    # Top 15 hospitals scatter plot
    data_top = hospital_summary.head(15)
    scatter = ax1.scatter(data_top['PATS'], data_top['AVG_CHARGE'], 
                         s=data_top['PATS']/10, alpha=0.6, 
                         c=data_top['AVG_CHARGE'], cmap='RdYlGn_r', 
                         edgecolors='black', linewidth=1)
    
    for _, row in data_top.iterrows():
        ax1.annotate(f"H{int(row['HOSPITAL_ID'])}", 
                    (row['PATS'], row['AVG_CHARGE']),
                    fontsize=8, ha='center')
    
    ax1.set_xlabel('Number of Admissions', fontsize=11, fontweight='bold')
    ax1.set_ylabel('Average Charge (USD)', fontsize=11, fontweight='bold')
    ax1.set_title('Hospital Cost vs Volume (Top 15)', fontsize=12, fontweight='bold')
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    
    cbar = plt.colorbar(scatter, ax=ax1)
    cbar.set_label('Avg Charge ($)', fontweight='bold')
    
    # Top hospitals by average charge
    data_expensive = hospital_summary.nlargest(15, 'AVG_CHARGE')
    bars = ax2.barh([f"Hospital {int(h)}" for h in data_expensive['HOSPITAL_ID']], 
                    data_expensive['AVG_CHARGE'], 
                    color=plt.cm.Spectral(np.linspace(0, 1, len(data_expensive))))
    
    ax2.set_xlabel('Average Charge per Admission (USD)', fontsize=11, fontweight='bold')
    ax2.set_title('Most Expensive Hospitals (by avg charge)', fontsize=12, fontweight='bold')
    ax2.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    
    for bar, val in zip(bars, data_expensive['AVG_CHARGE']):
        ax2.text(val + 1000, bar.get_y() + bar.get_height()/2, 
                f'${val:,.0f}', va='center', fontweight='bold', fontsize=9)
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '04_hospital_cost_analysis.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 04_hospital_cost_analysis.png")
    plt.close()

def plot_payer_analysis(payer_summary, substance_diag):
    """5. Payer type distribution and costs"""
    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(2, 2, hspace=0.3, wspace=0.3)
    
    # Clean payer data
    payer_clean = payer_summary.dropna(subset=['PAYER_TYPE']).sort_values('PATS', ascending=True)
    colors = plt.cm.Set3(np.linspace(0, 1, len(payer_clean)))
    
    # Pie chart
    ax1 = fig.add_subplot(gs[0, 0])
    wedges, texts, autotexts = ax1.pie(payer_clean['PATS'], 
                                        labels=payer_clean['PAYER_TYPE'],
                                        autopct='%1.1f%%',
                                        colors=colors,
                                        startangle=90,
                                        textprops={'fontsize': 10, 'weight': 'bold'})
    for autotext in autotexts:
        autotext.set_color('black')
        autotext.set_fontweight('bold')
    ax1.set_title('Substance Abuse Admissions by Payer Type', fontsize=12, fontweight='bold')
    
    # Admission volume bars
    ax2 = fig.add_subplot(gs[0, 1])
    bars = ax2.bar(range(len(payer_clean)), payer_clean['PATS'], color=colors)
    ax2.set_xticks(range(len(payer_clean)))
    ax2.set_xticklabels(payer_clean['PAYER_TYPE'], rotation=45, ha='right')
    ax2.set_ylabel('Number of Admissions', fontsize=11, fontweight='bold')
    ax2.set_title('Admission Volume by Payer', fontsize=12, fontweight='bold')
    ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{int(x/1000)}K'))
    
    for bar, val in zip(bars, payer_clean['PATS']):
        ax2.text(bar.get_x() + bar.get_width()/2, val + 50, 
                f'{int(val):,}', ha='center', fontweight='bold', fontsize=9)
    
    # Cost comparison
    ax3 = fig.add_subplot(gs[1, :])
    payer_costs = payer_clean.sort_values('AVG_CHARGE', ascending=True)
    colors_cost = plt.cm.RdYlGn_r(np.linspace(0.3, 0.7, len(payer_costs)))
    bars = ax3.barh(payer_costs['PAYER_TYPE'], payer_costs['AVG_CHARGE'], color=colors_cost)
    ax3.set_xlabel('Average Charge per Admission (USD)', fontsize=11, fontweight='bold')
    ax3.set_title('Average Cost by Payer Type', fontsize=12, fontweight='bold', pad=15)
    ax3.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    
    for bar, val in zip(bars, payer_costs['AVG_CHARGE']):
        ax3.text(val + 1000, bar.get_y() + bar.get_height()/2, 
                f'${val:,.0f}', va='center', fontweight='bold', fontsize=10)
    
    plt.savefig(VIZ_DIR / '05_payer_analysis.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 05_payer_analysis.png")
    plt.close()

def plot_category_by_hospital_heatmap(hospital_category):
    """6. Heatmap: Top hospitals vs substance categories"""
    # Get top 15 hospitals
    top_hospitals = hospital_category.groupby('HOSPITAL_ID')['PATS'].sum().nlargest(15).index
    
    # Create pivot table
    heatmap_data = hospital_category[hospital_category['HOSPITAL_ID'].isin(top_hospitals)].pivot_table(
        values='PATS',
        index='HOSPITAL_ID',
        columns='SUBSTANCE_CATEGORY',
        aggfunc='sum',
        fill_value=0
    )
    
    # Sort by total admissions
    heatmap_data['Total'] = heatmap_data.sum(axis=1)
    heatmap_data = heatmap_data.sort_values('Total', ascending=False).drop('Total', axis=1)
    
    fig, ax = plt.subplots(figsize=(14, 10))
    sns.heatmap(heatmap_data, annot=True, fmt='g', cmap='YlOrRd', 
                cbar_kws={'label': 'Admissions'}, ax=ax, linewidths=0.5)
    
    ax.set_title('Substance Abuse Admissions Heatmap\nTop 15 Hospitals vs Substance Categories', 
                fontsize=14, fontweight='bold', pad=20)
    ax.set_xlabel('Substance Category', fontsize=11, fontweight='bold')
    ax.set_ylabel('Hospital ID', fontsize=11, fontweight='bold')
    plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '06_hospital_category_heatmap.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 06_hospital_category_heatmap.png")
    plt.close()

def plot_payer_by_category(substance_diag):
    """7. Substance categories breakdown by payer type"""
    # Aggregate by category and payer
    payer_category = substance_diag.groupby(['SUBSTANCE_CATEGORY', 'PAYER_TYPE'])['PATS'].sum().reset_index()
    payer_category = payer_category.dropna(subset=['PAYER_TYPE'])
    
    # Get top categories
    top_categories = substance_diag.groupby('SUBSTANCE_CATEGORY')['PATS'].sum().nlargest(10).index
    filtered = payer_category[payer_category['SUBSTANCE_CATEGORY'].isin(top_categories)]
    
    fig, ax = plt.subplots(figsize=(14, 8))
    
    categories = filtered['SUBSTANCE_CATEGORY'].unique()
    payers = filtered['PAYER_TYPE'].unique()
    x = np.arange(len(categories))
    width = 0.2
    
    colors = plt.cm.Set2(np.linspace(0, 1, len(payers)))
    
    for i, payer in enumerate(sorted(payers)):
        data = filtered[filtered['PAYER_TYPE'] == payer].set_index('SUBSTANCE_CATEGORY')
        values = [data.loc[cat, 'PATS'] if cat in data.index else 0 for cat in categories]
        ax.bar(x + (i - len(payers)/2) * width, values, width, label=payer, color=colors[i])
    
    ax.set_xlabel('Substance Category', fontsize=11, fontweight='bold')
    ax.set_ylabel('Number of Admissions', fontsize=11, fontweight='bold')
    ax.set_title('Substance Abuse Admissions by Category & Payer Type', fontsize=14, fontweight='bold', pad=20)
    ax.set_xticks(x)
    ax.set_xticklabels(categories, rotation=45, ha='right')
    ax.legend(title='Payer Type', fontsize=10)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, p: f'{int(y/1000)}K'))
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '07_category_by_payer.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 07_category_by_payer.png")
    plt.close()

def plot_charge_vs_los_scatter(hospital_summary):
    """8. Charge vs Length of Stay scatter plot"""
    fig, ax = plt.subplots(figsize=(14, 9))
    
    # Create scatter with bubble size = admission volume
    scatter = ax.scatter(hospital_summary['AVG_LOS'], 
                        hospital_summary['AVG_CHARGE'],
                        s=hospital_summary['PATS']/5,
                        alpha=0.6,
                        c=hospital_summary['PATS'],
                        cmap='viridis',
                        edgecolors='black',
                        linewidth=0.5)
    
    # Annotate top 10 hospitals
    top_hospitals = hospital_summary.nlargest(10, 'PATS')
    for _, row in top_hospitals.iterrows():
        ax.annotate(f"H{int(row['HOSPITAL_ID'])}", 
                   (row['AVG_LOS'], row['AVG_CHARGE']),
                   fontsize=9, ha='center', fontweight='bold')
    
    ax.set_xlabel('Average Length of Stay (days)', fontsize=12, fontweight='bold')
    ax.set_ylabel('Average Charge per Admission (USD)', fontsize=12, fontweight='bold')
    ax.set_title('Hospital Cost vs Length of Stay\nBubble size = Volume of Substance Abuse Admissions', 
                fontsize=14, fontweight='bold', pad=20)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    
    cbar = plt.colorbar(scatter, ax=ax)
    cbar.set_label('Number of Admissions', fontweight='bold')
    
    plt.tight_layout()
    plt.savefig(VIZ_DIR / '08_charge_vs_los.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 08_charge_vs_los.png")
    plt.close()

def plot_cost_distribution_by_category(substance_diag):
    """9. Box plot of cost distribution by substance category"""
    # Get top 8 categories
    top_cats = substance_diag['SUBSTANCE_CATEGORY'].value_counts().head(8).index
    data_top = substance_diag[substance_diag['SUBSTANCE_CATEGORY'].isin(top_cats)].copy()
    
    fig, ax = plt.subplots(figsize=(14, 8))
    
    # Create box plot
    sns.boxplot(data=data_top, x='SUBSTANCE_CATEGORY', y='AVG_CHARGE', 
               palette='Set2', ax=ax)
    
    ax.set_xlabel('Substance Category', fontsize=12, fontweight='bold')
    ax.set_ylabel('Average Charge (USD)', fontsize=12, fontweight='bold')
    ax.set_title('Cost Distribution by Substance Category\n(Box Plot)', 
                fontsize=14, fontweight='bold', pad=20)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    plt.setp(ax.get_xticklabels(), rotation=45, ha='right')
    
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / '09_cost_distribution_boxplot.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 09_cost_distribution_boxplot.png")
    plt.close()

def plot_top_categories_detailed(substance_diag):
    """10. Detailed breakdown of top 5 substance categories"""
    top_5_cats = substance_diag['SUBSTANCE_CATEGORY'].value_counts().head(5).index
    
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    axes = axes.flatten()
    
    for idx, category in enumerate(top_5_cats):
        cat_data = substance_diag[substance_diag['SUBSTANCE_CATEGORY'] == category]
        
        # Top hospitals for this category
        top_hosp = cat_data.groupby('HOSPITAL_ID')['PATS'].sum().nlargest(8)
        
        ax = axes[idx]
        bars = ax.bar(range(len(top_hosp)), top_hosp.values,
                     color=plt.cm.viridis(np.linspace(0, 1, len(top_hosp))))
        ax.set_xticks(range(len(top_hosp)))
        ax.set_xticklabels([f"H{int(h)}" for h in top_hosp.index], rotation=45)
        ax.set_ylabel('Admissions', fontsize=10, fontweight='bold')
        ax.set_title(f'{category}\n({int(cat_data["PATS"].sum())} total)', 
                    fontsize=11, fontweight='bold')
        
        for bar, val in zip(bars, top_hosp.values):
            ax.text(bar.get_x() + bar.get_width()/2, val + 10,
                   f'{int(val)}', ha='center', fontsize=8, fontweight='bold')
    
    # Hide extra subplot
    axes[5].axis('off')
    
    fig.suptitle('Top 5 Substance Categories - Top Hospitals by Admissions',
                fontsize=14, fontweight='bold', y=1.00)
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / '10_top_categories_detail.png', dpi=300, bbox_inches='tight')
    print("✓ Saved: 10_top_categories_detail.png")
    plt.close()

def main():
    print("\n" + "="*80)
    print("SUBSTANCE ABUSE VISUALIZATION GENERATION")
    print("="*80)
    
    # Load processed data
    substance_diag, category_summary, hospital_summary, hospital_category, hospital_payer, payer_summary, msdrg_summary = load_processed_data()
    
    # Generate visualizations
    print("\n" + "="*80)
    print("CREATING VISUALIZATIONS")
    print("="*80)
    
    plot_substance_categories(category_summary)
    plot_category_costs(category_summary)
    plot_top_hospitals(hospital_summary)
    plot_hospital_costs(hospital_summary)
    plot_payer_analysis(payer_summary, substance_diag)
    plot_category_by_hospital_heatmap(hospital_category)
    plot_payer_by_category(substance_diag)
    plot_charge_vs_los_scatter(hospital_summary)
    plot_cost_distribution_by_category(substance_diag)
    plot_top_categories_detailed(substance_diag)
    
    print("\n" + "="*80)
    print("✓ VISUALIZATION GENERATION COMPLETE")
    print("="*80)
    print(f"\n10 comprehensive visualizations saved to: {OUTPUT_DIR.absolute()}/")
    print("\nGenerated files:")
    print("  01_substance_categories.png - Category admission counts")
    print("  02_category_costs_los.png - Cost and length of stay by category")
    print("  03_top_hospitals_substance.png - Top 20 hospitals")
    print("  04_hospital_cost_analysis.png - Cost vs volume analysis")
    print("  05_payer_analysis.png - Payer type breakdown")
    print("  06_hospital_category_heatmap.png - Hospital vs category heatmap")
    print("  07_category_by_payer.png - Categories by payer distribution")
    print("  08_charge_vs_los.png - Charge vs hospital stay scatter")
    print("  09_cost_distribution_boxplot.png - Cost distribution by category")
    print("  10_top_categories_detail.png - Detailed category breakdowns")

if __name__ == '__main__':
    main()
